name: ci-test

on:
  push:
    branches: [ "github-action" ]
  pull_request:
    branches: [ "github-action " ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:    

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: make test
